{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ required "you must specify a access key id" .Values.minio.access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "you must specify secret access key" .Values.minio.secret_access_key | b64enc }}
{{- end }}
